FROM node:10-slim

RUN apt-get update || : && apt-get -y install bluetooth bluez libbluetooth-dev libudev-dev build-essential make python

WORKDIR /app/

COPY package*.json ./

RUN npm install --production

COPY app.js ./

USER root

CMD ["node", "app.js"]
